name: Build and push CKAN 2.9 images (alpine)

on: push

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-docker-publish.yml
    with:
      ckan-major-version: "2.9"
      ckan-version: "ckan-2.9.11"
      base-tags: "ckan/ckan-base:2.9,ckan/ckan-base:2.9.11"
      dev-tags: "ckan/ckan-dev:2.9,ckan/ckan-dev:2.9.11"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
